### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by chamilion18** [kahk/Automatizacion_CGI#1]
tiene base de datos ?

**Comment by chamilion18** [comment]
me interesa implementar tu proyecto en la empresa donde laboro.

**Comment by oscar-irribarra** [comment]
Si le sirve de alguna manera adelante puede utilizarlo. (en lo posible dejar alguna referencia a este repositorio en el proyecto)

pd: Acabo de incluir el script SQL.

Saludos,

**Comment by chamilion18** [comment]
Hola buenos días, gracias por poner la base de datos. 

en que programa esta hecho ? o como lo puedo implementar?
